/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminPanelRouteImport } from './routes/admin/_panel'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPracticeRouteImport } from './routes/_app/practice'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppContributeRouteImport } from './routes/_app/contribute'
import { Route as AppSubjectsIndexRouteImport } from './routes/_app/subjects.index'
import { Route as AdminPanelWorksheetsRouteImport } from './routes/admin/_panel/worksheets'
import { Route as AdminPanelSubjectsRouteImport } from './routes/admin/_panel/subjects'
import { Route as AdminPanelStudentsRouteImport } from './routes/admin/_panel/students'
import { Route as AdminPanelPracticePapersRouteImport } from './routes/admin/_panel/practice-papers'
import { Route as AdminPanelPastPapersRouteImport } from './routes/admin/_panel/past-papers'
import { Route as AdminPanelOnePagersRouteImport } from './routes/admin/_panel/one-pagers'
import { Route as AdminPanelNotesRouteImport } from './routes/admin/_panel/notes'
import { Route as AdminPanelInviteCodesRouteImport } from './routes/admin/_panel/invite-codes'
import { Route as AdminPanelImportantQuestionsRouteImport } from './routes/admin/_panel/important-questions'
import { Route as AdminPanelFormulaSheetsRouteImport } from './routes/admin/_panel/formula-sheets'
import { Route as AdminPanelExamScheduleRouteImport } from './routes/admin/_panel/exam-schedule'
import { Route as AdminPanelDashboardRouteImport } from './routes/admin/_panel/dashboard'
import { Route as AdminPanelContributionsRouteImport } from './routes/admin/_panel/contributions'
import { Route as AdminPanelChaptersRouteImport } from './routes/admin/_panel/chapters'
import { Route as AppSubjectsSubjectIdIndexRouteImport } from './routes/_app/subjects.$subjectId.index'
import { Route as AppSubjectsSubjectIdChapterIdRouteImport } from './routes/_app/subjects.$subjectId.$chapterId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPanelRoute = AdminPanelRouteImport.update({
  id: '/_panel',
  getParentRoute: () => AdminRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeRoute = AppPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppContributeRoute = AppContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsIndexRoute = AppSubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => AppRoute,
} as any)
const AdminPanelWorksheetsRoute = AdminPanelWorksheetsRouteImport.update({
  id: '/worksheets',
  path: '/worksheets',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelSubjectsRoute = AdminPanelSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelStudentsRoute = AdminPanelStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelPracticePapersRoute =
  AdminPanelPracticePapersRouteImport.update({
    id: '/practice-papers',
    path: '/practice-papers',
    getParentRoute: () => AdminPanelRoute,
  } as any)
const AdminPanelPastPapersRoute = AdminPanelPastPapersRouteImport.update({
  id: '/past-papers',
  path: '/past-papers',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelOnePagersRoute = AdminPanelOnePagersRouteImport.update({
  id: '/one-pagers',
  path: '/one-pagers',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelNotesRoute = AdminPanelNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelInviteCodesRoute = AdminPanelInviteCodesRouteImport.update({
  id: '/invite-codes',
  path: '/invite-codes',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelImportantQuestionsRoute =
  AdminPanelImportantQuestionsRouteImport.update({
    id: '/important-questions',
    path: '/important-questions',
    getParentRoute: () => AdminPanelRoute,
  } as any)
const AdminPanelFormulaSheetsRoute = AdminPanelFormulaSheetsRouteImport.update({
  id: '/formula-sheets',
  path: '/formula-sheets',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelExamScheduleRoute = AdminPanelExamScheduleRouteImport.update({
  id: '/exam-schedule',
  path: '/exam-schedule',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelDashboardRoute = AdminPanelDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelContributionsRoute = AdminPanelContributionsRouteImport.update({
  id: '/contributions',
  path: '/contributions',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelChaptersRoute = AdminPanelChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AppSubjectsSubjectIdIndexRoute =
  AppSubjectsSubjectIdIndexRouteImport.update({
    id: '/subjects/$subjectId/',
    path: '/subjects/$subjectId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppSubjectsSubjectIdChapterIdRoute =
  AppSubjectsSubjectIdChapterIdRouteImport.update({
    id: '/subjects/$subjectId/$chapterId',
    path: '/subjects/$subjectId/$chapterId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminPanelRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/contribute': typeof AppContributeRoute
  '/home': typeof AppHomeRoute
  '/practice': typeof AppPracticeRoute
  '/profile': typeof AppProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/chapters': typeof AdminPanelChaptersRoute
  '/admin/contributions': typeof AdminPanelContributionsRoute
  '/admin/dashboard': typeof AdminPanelDashboardRoute
  '/admin/exam-schedule': typeof AdminPanelExamScheduleRoute
  '/admin/formula-sheets': typeof AdminPanelFormulaSheetsRoute
  '/admin/important-questions': typeof AdminPanelImportantQuestionsRoute
  '/admin/invite-codes': typeof AdminPanelInviteCodesRoute
  '/admin/notes': typeof AdminPanelNotesRoute
  '/admin/one-pagers': typeof AdminPanelOnePagersRoute
  '/admin/past-papers': typeof AdminPanelPastPapersRoute
  '/admin/practice-papers': typeof AdminPanelPracticePapersRoute
  '/admin/students': typeof AdminPanelStudentsRoute
  '/admin/subjects': typeof AdminPanelSubjectsRoute
  '/admin/worksheets': typeof AdminPanelWorksheetsRoute
  '/subjects/': typeof AppSubjectsIndexRoute
  '/subjects/$subjectId/$chapterId': typeof AppSubjectsSubjectIdChapterIdRoute
  '/subjects/$subjectId/': typeof AppSubjectsSubjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/contribute': typeof AppContributeRoute
  '/home': typeof AppHomeRoute
  '/practice': typeof AppPracticeRoute
  '/profile': typeof AppProfileRoute
  '/admin': typeof AdminIndexRoute
  '/admin/chapters': typeof AdminPanelChaptersRoute
  '/admin/contributions': typeof AdminPanelContributionsRoute
  '/admin/dashboard': typeof AdminPanelDashboardRoute
  '/admin/exam-schedule': typeof AdminPanelExamScheduleRoute
  '/admin/formula-sheets': typeof AdminPanelFormulaSheetsRoute
  '/admin/important-questions': typeof AdminPanelImportantQuestionsRoute
  '/admin/invite-codes': typeof AdminPanelInviteCodesRoute
  '/admin/notes': typeof AdminPanelNotesRoute
  '/admin/one-pagers': typeof AdminPanelOnePagersRoute
  '/admin/past-papers': typeof AdminPanelPastPapersRoute
  '/admin/practice-papers': typeof AdminPanelPracticePapersRoute
  '/admin/students': typeof AdminPanelStudentsRoute
  '/admin/subjects': typeof AdminPanelSubjectsRoute
  '/admin/worksheets': typeof AdminPanelWorksheetsRoute
  '/subjects': typeof AppSubjectsIndexRoute
  '/subjects/$subjectId/$chapterId': typeof AppSubjectsSubjectIdChapterIdRoute
  '/subjects/$subjectId': typeof AppSubjectsSubjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/contribute': typeof AppContributeRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/practice': typeof AppPracticeRoute
  '/_app/profile': typeof AppProfileRoute
  '/admin/_panel': typeof AdminPanelRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/_panel/chapters': typeof AdminPanelChaptersRoute
  '/admin/_panel/contributions': typeof AdminPanelContributionsRoute
  '/admin/_panel/dashboard': typeof AdminPanelDashboardRoute
  '/admin/_panel/exam-schedule': typeof AdminPanelExamScheduleRoute
  '/admin/_panel/formula-sheets': typeof AdminPanelFormulaSheetsRoute
  '/admin/_panel/important-questions': typeof AdminPanelImportantQuestionsRoute
  '/admin/_panel/invite-codes': typeof AdminPanelInviteCodesRoute
  '/admin/_panel/notes': typeof AdminPanelNotesRoute
  '/admin/_panel/one-pagers': typeof AdminPanelOnePagersRoute
  '/admin/_panel/past-papers': typeof AdminPanelPastPapersRoute
  '/admin/_panel/practice-papers': typeof AdminPanelPracticePapersRoute
  '/admin/_panel/students': typeof AdminPanelStudentsRoute
  '/admin/_panel/subjects': typeof AdminPanelSubjectsRoute
  '/admin/_panel/worksheets': typeof AdminPanelWorksheetsRoute
  '/_app/subjects/': typeof AppSubjectsIndexRoute
  '/_app/subjects/$subjectId/$chapterId': typeof AppSubjectsSubjectIdChapterIdRoute
  '/_app/subjects/$subjectId/': typeof AppSubjectsSubjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/contribute'
    | '/home'
    | '/practice'
    | '/profile'
    | '/admin/'
    | '/admin/chapters'
    | '/admin/contributions'
    | '/admin/dashboard'
    | '/admin/exam-schedule'
    | '/admin/formula-sheets'
    | '/admin/important-questions'
    | '/admin/invite-codes'
    | '/admin/notes'
    | '/admin/one-pagers'
    | '/admin/past-papers'
    | '/admin/practice-papers'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/worksheets'
    | '/subjects/'
    | '/subjects/$subjectId/$chapterId'
    | '/subjects/$subjectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/contribute'
    | '/home'
    | '/practice'
    | '/profile'
    | '/admin'
    | '/admin/chapters'
    | '/admin/contributions'
    | '/admin/dashboard'
    | '/admin/exam-schedule'
    | '/admin/formula-sheets'
    | '/admin/important-questions'
    | '/admin/invite-codes'
    | '/admin/notes'
    | '/admin/one-pagers'
    | '/admin/past-papers'
    | '/admin/practice-papers'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/worksheets'
    | '/subjects'
    | '/subjects/$subjectId/$chapterId'
    | '/subjects/$subjectId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/login'
    | '/signup'
    | '/_app/contribute'
    | '/_app/home'
    | '/_app/practice'
    | '/_app/profile'
    | '/admin/_panel'
    | '/admin/'
    | '/admin/_panel/chapters'
    | '/admin/_panel/contributions'
    | '/admin/_panel/dashboard'
    | '/admin/_panel/exam-schedule'
    | '/admin/_panel/formula-sheets'
    | '/admin/_panel/important-questions'
    | '/admin/_panel/invite-codes'
    | '/admin/_panel/notes'
    | '/admin/_panel/one-pagers'
    | '/admin/_panel/past-papers'
    | '/admin/_panel/practice-papers'
    | '/admin/_panel/students'
    | '/admin/_panel/subjects'
    | '/admin/_panel/worksheets'
    | '/_app/subjects/'
    | '/_app/subjects/$subjectId/$chapterId'
    | '/_app/subjects/$subjectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_panel': {
      id: '/admin/_panel'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminPanelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice': {
      id: '/_app/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AppPracticeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contribute': {
      id: '/_app/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof AppContributeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subjects/': {
      id: '/_app/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof AppSubjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/_panel/worksheets': {
      id: '/admin/_panel/worksheets'
      path: '/worksheets'
      fullPath: '/admin/worksheets'
      preLoaderRoute: typeof AdminPanelWorksheetsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/subjects': {
      id: '/admin/_panel/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminPanelSubjectsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/students': {
      id: '/admin/_panel/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminPanelStudentsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/practice-papers': {
      id: '/admin/_panel/practice-papers'
      path: '/practice-papers'
      fullPath: '/admin/practice-papers'
      preLoaderRoute: typeof AdminPanelPracticePapersRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/past-papers': {
      id: '/admin/_panel/past-papers'
      path: '/past-papers'
      fullPath: '/admin/past-papers'
      preLoaderRoute: typeof AdminPanelPastPapersRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/one-pagers': {
      id: '/admin/_panel/one-pagers'
      path: '/one-pagers'
      fullPath: '/admin/one-pagers'
      preLoaderRoute: typeof AdminPanelOnePagersRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/notes': {
      id: '/admin/_panel/notes'
      path: '/notes'
      fullPath: '/admin/notes'
      preLoaderRoute: typeof AdminPanelNotesRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/invite-codes': {
      id: '/admin/_panel/invite-codes'
      path: '/invite-codes'
      fullPath: '/admin/invite-codes'
      preLoaderRoute: typeof AdminPanelInviteCodesRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/important-questions': {
      id: '/admin/_panel/important-questions'
      path: '/important-questions'
      fullPath: '/admin/important-questions'
      preLoaderRoute: typeof AdminPanelImportantQuestionsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/formula-sheets': {
      id: '/admin/_panel/formula-sheets'
      path: '/formula-sheets'
      fullPath: '/admin/formula-sheets'
      preLoaderRoute: typeof AdminPanelFormulaSheetsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/exam-schedule': {
      id: '/admin/_panel/exam-schedule'
      path: '/exam-schedule'
      fullPath: '/admin/exam-schedule'
      preLoaderRoute: typeof AdminPanelExamScheduleRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/dashboard': {
      id: '/admin/_panel/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminPanelDashboardRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/contributions': {
      id: '/admin/_panel/contributions'
      path: '/contributions'
      fullPath: '/admin/contributions'
      preLoaderRoute: typeof AdminPanelContributionsRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin/_panel/chapters': {
      id: '/admin/_panel/chapters'
      path: '/chapters'
      fullPath: '/admin/chapters'
      preLoaderRoute: typeof AdminPanelChaptersRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/_app/subjects/$subjectId/': {
      id: '/_app/subjects/$subjectId/'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId/'
      preLoaderRoute: typeof AppSubjectsSubjectIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subjects/$subjectId/$chapterId': {
      id: '/_app/subjects/$subjectId/$chapterId'
      path: '/subjects/$subjectId/$chapterId'
      fullPath: '/subjects/$subjectId/$chapterId'
      preLoaderRoute: typeof AppSubjectsSubjectIdChapterIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppContributeRoute: typeof AppContributeRoute
  AppHomeRoute: typeof AppHomeRoute
  AppPracticeRoute: typeof AppPracticeRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSubjectsIndexRoute: typeof AppSubjectsIndexRoute
  AppSubjectsSubjectIdChapterIdRoute: typeof AppSubjectsSubjectIdChapterIdRoute
  AppSubjectsSubjectIdIndexRoute: typeof AppSubjectsSubjectIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContributeRoute: AppContributeRoute,
  AppHomeRoute: AppHomeRoute,
  AppPracticeRoute: AppPracticeRoute,
  AppProfileRoute: AppProfileRoute,
  AppSubjectsIndexRoute: AppSubjectsIndexRoute,
  AppSubjectsSubjectIdChapterIdRoute: AppSubjectsSubjectIdChapterIdRoute,
  AppSubjectsSubjectIdIndexRoute: AppSubjectsSubjectIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminPanelRouteChildren {
  AdminPanelChaptersRoute: typeof AdminPanelChaptersRoute
  AdminPanelContributionsRoute: typeof AdminPanelContributionsRoute
  AdminPanelDashboardRoute: typeof AdminPanelDashboardRoute
  AdminPanelExamScheduleRoute: typeof AdminPanelExamScheduleRoute
  AdminPanelFormulaSheetsRoute: typeof AdminPanelFormulaSheetsRoute
  AdminPanelImportantQuestionsRoute: typeof AdminPanelImportantQuestionsRoute
  AdminPanelInviteCodesRoute: typeof AdminPanelInviteCodesRoute
  AdminPanelNotesRoute: typeof AdminPanelNotesRoute
  AdminPanelOnePagersRoute: typeof AdminPanelOnePagersRoute
  AdminPanelPastPapersRoute: typeof AdminPanelPastPapersRoute
  AdminPanelPracticePapersRoute: typeof AdminPanelPracticePapersRoute
  AdminPanelStudentsRoute: typeof AdminPanelStudentsRoute
  AdminPanelSubjectsRoute: typeof AdminPanelSubjectsRoute
  AdminPanelWorksheetsRoute: typeof AdminPanelWorksheetsRoute
}

const AdminPanelRouteChildren: AdminPanelRouteChildren = {
  AdminPanelChaptersRoute: AdminPanelChaptersRoute,
  AdminPanelContributionsRoute: AdminPanelContributionsRoute,
  AdminPanelDashboardRoute: AdminPanelDashboardRoute,
  AdminPanelExamScheduleRoute: AdminPanelExamScheduleRoute,
  AdminPanelFormulaSheetsRoute: AdminPanelFormulaSheetsRoute,
  AdminPanelImportantQuestionsRoute: AdminPanelImportantQuestionsRoute,
  AdminPanelInviteCodesRoute: AdminPanelInviteCodesRoute,
  AdminPanelNotesRoute: AdminPanelNotesRoute,
  AdminPanelOnePagersRoute: AdminPanelOnePagersRoute,
  AdminPanelPastPapersRoute: AdminPanelPastPapersRoute,
  AdminPanelPracticePapersRoute: AdminPanelPracticePapersRoute,
  AdminPanelStudentsRoute: AdminPanelStudentsRoute,
  AdminPanelSubjectsRoute: AdminPanelSubjectsRoute,
  AdminPanelWorksheetsRoute: AdminPanelWorksheetsRoute,
}

const AdminPanelRouteWithChildren = AdminPanelRoute._addFileChildren(
  AdminPanelRouteChildren,
)

interface AdminRouteChildren {
  AdminPanelRoute: typeof AdminPanelRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPanelRoute: AdminPanelRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
